name: Repository Events
on:
  push:
    branches:
      - main
      - "feature/*"
    paths:
      - "abc.txt"    
      
   
jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v4
